name: AboutGoogle.org
favicon: null
layout_spectrum: 0.7474465074483305
typography_spectrum: 0.5465346490964293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.03421126143075526
  lightness: 0.9603687054477632
  saturation: 0.25812346604652703
  rhythmicContrast: 0.1259012611117214
purpose: []
